package kurento

import "fmt"

type IWebRtcEndpoint interface {
	GatherCandidates() error

	AddIceCandidate(candidate IceCandidate) error

	CreateDataChannel(label string, ordered bool, maxPacketLifeTime int, maxRetransmits int, protocol string) error

	CloseDataChannel(channelId int) error
}

/*<p>       Control interface for Kurento WebRTC endpoint.       </p>       <p>       This endpoint is one side of a peer-to-peer WebRTC communication, being the other peer a WebRTC capable browser -using the RTCPeerConnection API-, a native WebRTC app or even another Kurento Media Server.       </p>       <p>       In order to establish a WebRTC communication, peers engage in an SDP negotiation process, where one of the peers (the offerer) sends an offer, while the other peer (the offeree) responds with an answer. This endpoint can function in both situations       <ul>         <li>           As offerer: The negotiation process is initiated by the media server           <ul style='list-style-type:circle'>             <li>KMS generates the SDP offer through the <code>generateOffer</code> method. This <i>offer</i> must then be sent to the remote peer (the offeree) through the signaling channel, for processing.</li>             <li>The remote peer process the <i>offer</i>, and generates an <i>answer</i> to this <i>offer</i>. The <i>answer</i> is sent back to the media server.</li>             <li>Upon receiving the <i>answer</i>, the endpoint must invoke the <code>processAnswer</code> method.</li>           </ul>         </li>         <li>           As offeree: The negotiation process is initiated by the remote peer           <ul>             <li>The remote peer, acting as offerer, generates an SDP <i>offer</i> and sends it to the WebRTC endpoint in Kurento.</li>             <li>The endpoint will process the <i>offer</i> invoking the <code>processOffer</code> method. The result of this method will be a string, containing an SDP <i>answer</i>.</li>             <li>The SDP <i>answer</i> must be sent back to the offerer, so it can be processed.</li>           </ul>         </li>       </ul>       </p>       <p>       SDPs are sent without ICE candidates, following the Trickle ICE optimization. Once the SDP negotiation is completed, both peers proceed with the ICE discovery process, intended to set up a bidirectional media connection. During this process, each peer       <ul>         <li>Discovers ICE candidates for itself, containing pairs of IPs and ports.</li>         <li>ICE candidates are sent via the signaling channel as they are discovered, to the remote peer for probing.</li>         <li>ICE connectivity checks are run as soon as the new candidate description, from the remote peer, is available.</li>       </ul>       Once a suitable pair of candidates (one for each peer) is discovered, the media session can start. The harvesting process in Kurento, begins with the invocation of the <code>gatherCandidates</code> method. Since the whole Trickle ICE purpose is to speed-up connectivity, candidates are generated asynchronously. Therefore, in order to capture the candidates, the user must subscribe to the event <code>IceCandidateFound</code>. It is important that the event listener is bound before invoking <code>gatherCandidates</code>, otherwise a suitable candidate might be lost, and connection might not be established.       </p>       <p>       It's important to keep in mind that WebRTC connection is an asynchronous process, when designing interactions between different MediaElements. For example, it would be pointless to start recording before media is flowing. In order to be notified of state changes, the application can subscribe to events generated by the WebRtcEndpoint. Following is a full list of events generated by WebRtcEndpoint:       <ul>         <li>           <code>IceComponentStateChange</code>: This event informs only about changes in the ICE connection state. Possible values are:           <ul style='list-style-type:circle'>             <li><code>DISCONNECTED</code>: No activity scheduled</li>             <li><code>GATHERING</code>: Gathering local candidates</li>             <li><code>CONNECTING</code>: Establishing connectivity</li>             <li><code>CONNECTED</code>: At least one working candidate pair</li>             <li><code>READY</code>: ICE concluded, candidate pair selection is now final</li>             <li><code>FAILED</code>: Connectivity checks have been completed, but media connection was not established</li>           </ul>           The transitions between states are covered in RFC5245.           It could be said that it's network-only, as it only takes into account the state of the network connection, ignoring other higher level stuff, like DTLS handshake, RTCP flow, etc.  This implies that, while the component state is <code>CONNECTED</code>, there might be no media flowing between the peers. This makes this event useful only to receive low-level information about the connection between peers. Even more, while other events might leave a graceful period of time before firing, this event fires immediately after the state change is detected.         </li>         <li>           <code>IceCandidateFound</code>: Raised when a new candidate is discovered. ICE candidates must be sent to the remote peer of the connection. Failing to do so for some or all of the candidates might render the connection unusable.         </li>         <li>           <code>IceGatheringDone</code>: Raised when the ICE harvesting process is completed. This means that all candidates have already been discovered.         </li>         <li>           <code>NewCandidatePairSelected</code>: Raised when a new ICE candidate pair gets selected. The pair contains both local and remote candidates being used for a component. This event can be raised during a media session, if a new pair of candidates with higher priority in the link are found.         </li>         <li>           <code>DataChannelOpen</code>: Raised when a data channel is open.         </li>         <li>           <code>DataChannelClose</code>: Raised when a data channel is closed.         </li>       </ul>       </p>       <p>       Registering to any of above events requires the application to provide a callback function. Each event provides different information, so it is recommended to consult the signature of the event listeners.       </p>       <p>       Flow control and congestion management is one of the most important features of WebRTC. WebRTC connections start with the lowest bandwidth configured and slowly ramps up to the maximum available bandwidth, or to the higher limit of the exploration range in case no bandwidth limitation is detected. Notice that WebRtcEndpoints in Kurento are designed in a way that multiple WebRTC connections fed by the same stream share quality. When a new connection is added, as it requires to start with low bandwidth, it will cause the rest of connections to experience a transient period of degraded quality, until it stabilizes its bitrate. This doesn't apply when transcoding is involved. Transcoders will adjust their output bitrate based in bandwidth requirements, but it won't affect the original stream. If an incoming WebRTC stream needs to be transcoded, for whatever reason, all WebRtcEndpoints fed from transcoder output will share a separate quality than the ones connected directly to the original stream.       </p>       <p>       The default bandwidth range of the endpoint is 100kbps-500kbps, but it can be changed separately for input/output directions and for audio/video streams.       <ul>         <li>           Input bandwidth control mechanism: Configuration interval used to inform remote peer the range of bitrates that can be pushed into this WebRtcEndpoint object.           <ul style='list-style-type:circle'>             <li>               setMin/MaxVideoRecvBandwidth: sets Min/Max bitrate limits expected for received video stream.             </li>             <li>               setMin/MaxAudioRecvBandwidth: sets Min/Max bitrate limits expected for received audio stream.             </li>           </ul>           Max values are announced in the SDP, while min values are set to limit the lower value of REMB packages. It follows that min values will only have effect in peers that support this control mechanism, such as Chrome.         </li>         <li>           Output bandwidth control mechanism: Configuration interval used to control bitrate of the output video stream sent to remote peer. It is important to keep in mind that pushed bitrate depends on network and remote peer capabilities. Remote peers can also announce bandwidth limitation in their SDPs (through the <code>b=<modifier>:<value></code> tag). Kurento will always enforce bitrate limitations specified by the remote peer over internal configurations.           <ul style='list-style-type:circle'>             <li>               setMin/MaxVideoSendBandwidth: sets Min/Max bitrate limits  for video sent to remote peer             </li>           </ul>         </li>       </ul>       All bandwidth control parameters must be changed before the SDP negotiation takes place, and can't be changed afterwards.       </p>       <p>       DataChannels allow other media elements that make use of the DataPad, to send arbitrary data. For instance, if there is a filter that publishes event information, it'll be sent to the remote peer through the channel. There is no API available for programmers to make use of this feature in the WebRtcElement. DataChannels can be configured to provide the following:       <ul>         <li>           Reliable or partially reliable delivery of sent messages         </li>         <li>           In-order or out-of-order delivery of sent messages         </li>       </ul>       Unreliable, out-of-order delivery is equivalent to raw UDP semantics. The message may make it, or it may not, and order is not important. However, the channel can be configured to be <i>partially reliable</i> by specifying the maximum number of retransmissions or setting a time limit for retransmissions: the WebRTC stack will handle the acknowledgments and timeouts.       </p>       <p>       The possibility to create DataChannels in a WebRtcEndpoint must be explicitly enabled when creating the endpoint, as this feature is disabled by default. If this is the case, they can be created invoking the createDataChannel method. The arguments for this method, all of them optional, provide the necessary configuration:       <ul>         <li>          <code>label</code>: assigns a label to the DataChannel. This can help identify each possible channel separately.         </li>         <li>           <code>ordered</code>: specifies if the DataChannel guarantees order, which is the default mode. If maxPacketLifetime and maxRetransmits have not been set, this enables reliable mode.         </li>         <li>           <code>maxPacketLifeTime</code>: The time window in milliseconds, during which transmissions and retransmissions may take place in unreliable mode. This forces unreliable mode, even if <code>ordered</code> has been activated.         </li>         <li>           <code>maxRetransmits</code>: maximum number of retransmissions that are attempted in unreliable mode. This forces unreliable mode, even if <code>ordered</code> has been activated.         </li>         <li>           <code>Protocol</code>: Name of the subprotocol used for data communication.         </li>       </ul>*/
type WebRtcEndpoint struct {
	BaseRtpEndpoint

	/*address of the STUN server (Only IP address are supported)*/
	StunServerAddress string

	/*port of the STUN server*/
	StunServerPort Iint

	/*TURN server URL with this format: <code>user:password@address:port(?transport=[udp|tcp|tls])</code>.</br><code>address</code> must be an IP (not a domain).</br><code>transport</code> is optional (UDP by default).*/
	TurnUrl string

	/*the ICE candidate pair (local and remote candidates) used by the ice library for each stream.*/
	ICECandidatePairs []*IceCandidatePair

	/*the ICE connection state for all the connections.*/
	IceConnectionState []*IceConnection
}

// Return Constructor Params to be called by "Create".
func (elem *WebRtcEndpoint) getConstuctorParams(from IMediaObject, options map[string]interface{}) map[string]interface{} {

	// Create basic constructor params
	ret := map[string]interface{}{
		"mediaPipeline":      fmt.Sprintf("%s", from),
		"useDataChannels":    fmt.Sprintf("%s", from),
		"certificateKeyType": fmt.Sprintf("%s", from),
	}

	mergeOptions(ret, options)
	return ret

}

/*Start the gathering of ICE candidates.</br>It must be called after SdpEndpoint::generateOffer or SdpEndpoint::processOffer for Trickle ICE. If invoked before generating or processing an SDP offer, the candidates gathered will be added to the SDP processed.*/

func (elem *WebRtcEndpoint) GatherCandidates() error {
	req := elem.getInvokeRequest()

	req["params"] = map[string]interface{}{
		"operation": "gatherCandidates",
		"object":    elem.Id,
	}

	// call server and and wait response
	response := <-elem.connection.Request(req)

	return response.Error

}

/*Process an ICE candidate sent by the remote peer of the connection.*/

func (elem *WebRtcEndpoint) AddIceCandidate(candidate IceCandidate) error {
	req := elem.getInvokeRequest()

	params := make(map[string]interface{})

	setIfNotEmpty(params, "candidate", candidate)

	req["params"] = map[string]interface{}{
		"operation": "addIceCandidate",
		"object":    elem.Id,

		"operationParams": params,
	}

	// call server and and wait response
	response := <-elem.connection.Request(req)

	return response.Error

}

/*Create a new data channel, if data channels are supported. If they are not supported, this method throws an exception.           Being supported means that the WebRtcEndpoint has been created with data channel support, the client also supports data channels, and they have been negotaited in the SDP exchange.           Otherwise, the method throws an exception, indicating that the operation is not possible.</br>           Data channels can work in either unreliable mode (analogous to User Datagram Protocol or UDP) or reliable mode (analogous to Transmission Control Protocol or TCP).           The two modes have a simple distinction:           <ul>             <li>Reliable mode guarantees the transmission of messages and also the order in which they are delivered. This takes extra overhead, thus potentially making this mode slower.</li>             <li>Unreliable mode does not guarantee every message will get to the other side nor what order they get there. This removes the overhead, allowing this mode to work much faster.</li>           </ul>*/

func (elem *WebRtcEndpoint) CreateDataChannel(label string, ordered bool, maxPacketLifeTime int, maxRetransmits int, protocol string) error {
	req := elem.getInvokeRequest()

	params := make(map[string]interface{})

	setIfNotEmpty(params, "label", label)

	setIfNotEmpty(params, "ordered", ordered)

	setIfNotEmpty(params, "maxPacketLifeTime", maxPacketLifeTime)

	setIfNotEmpty(params, "maxRetransmits", maxRetransmits)

	setIfNotEmpty(params, "protocol", protocol)

	req["params"] = map[string]interface{}{
		"operation": "createDataChannel",
		"object":    elem.Id,

		"operationParams": params,
	}

	// call server and and wait response
	response := <-elem.connection.Request(req)

	return response.Error

}

/*Closes an open data channel*/

func (elem *WebRtcEndpoint) CloseDataChannel(channelId int) error {
	req := elem.getInvokeRequest()

	params := make(map[string]interface{})

	setIfNotEmpty(params, "channelId", channelId)

	req["params"] = map[string]interface{}{
		"operation": "closeDataChannel",
		"object":    elem.Id,

		"operationParams": params,
	}

	// call server and and wait response
	response := <-elem.connection.Request(req)

	return response.Error

}
